"""ZPI-16: Zmiana taryf na rozdzielczosc 15-minutowa

Revision ID: 273fe71700b4
Revises: e35af0e7da65
Create Date: 2026-05-19 14:18:48.172909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273fe71700b4'
down_revision: Union[str, Sequence[str], None] = 'e35af0e7da65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_rates', sa.Column('time_start', sa.Time(), nullable=False))
    op.add_column('tariff_rates', sa.Column('time_end', sa.Time(), nullable=False))
    op.drop_column('tariff_rates', 'hour_end')
    op.drop_column('tariff_rates', 'hour_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff_rates', sa.Column('hour_start', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tariff_rates', sa.Column('hour_end', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tariff_rates', 'time_end')
    op.drop_column('tariff_rates', 'time_start')
    # ### end Alembic commands ###
